USE cursedR;

SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE Partida_Armas;
TRUNCATE TABLE Partida_Objetos;
TRUNCATE TABLE Partida_Enemigo;
TRUNCATE TABLE Partida;
TRUNCATE TABLE Jugador;
TRUNCATE TABLE Objetos;
TRUNCATE TABLE Armas;
TRUNCATE TABLE Enemigo;
TRUNCATE TABLE Clases;
TRUNCATE TABLE Recompensas;
SET FOREIGN_KEY_CHECKS = 1;

ALTER TABLE Recompensas AUTO_INCREMENT = 1;
ALTER TABLE Clases AUTO_INCREMENT = 1;
ALTER TABLE Enemigo AUTO_INCREMENT = 1;
ALTER TABLE Armas AUTO_INCREMENT = 1;
ALTER TABLE Objetos AUTO_INCREMENT = 1;
ALTER TABLE Jugador AUTO_INCREMENT = 1;
ALTER TABLE Partida AUTO_INCREMENT = 1;